My Project: Time Class Reference
Time Class Reference
#include <time.h>
Public Member Functions
Time ()
default constructor
Time (int hrs, int mins)
Overloaded constructor.
void setHrs (int hrs)
Set hours.
int getHrs () const
Gets hours.
void setMins (int mins)
Set minute.
int getMins () const
Gets minutes.
std::string getTimeString () const
Combines hours and minutes as a string.
Private Attributes
int m_mins
int m_hrs
Detailed Description
Definition at line 22 of file time.h.
Constructor & Destructor Documentation
Time() [1/2]
Time::Time ()
default constructor
Definition at line 6 of file time.cpp.
 {
     m_hrs = 0;
     m_mins = 0;
 }
References m_hrs, and m_mins.
Time() [2/2]
Time::Time (int hrs, int mins)
Overloaded constructor.
Parameters
hours,minutes
Definition at line 12 of file time.cpp.
 {
     m_hrs = hrs;
     m_mins = mins;
 }
References m_hrs, and m_mins.
Referenced by testParamConstruct().
Member Function Documentation
getHrs()
int Time::getHrs () const
Gets hours.
Returns
hours
Definition at line 19 of file time.cpp.
 {return m_hrs;}
References m_hrs.
Referenced by testSetGet().
getMins()
int Time::getMins () const
Gets minutes.
Returns
minutes
Definition at line 22 of file time.cpp.
 {return m_mins;}
References m_mins.
Referenced by testSetGet().
getTimeString()
std::string Time::getTimeString () const
Combines hours and minutes as a string.
Returns
the time as a string
Definition at line 24 of file time.cpp.
 {
     return(std::to_string(m_hrs) + ":" + std::to_string(m_mins));
 }
References m_hrs, and m_mins.
Referenced by testConstruct(), testParamConstruct(), and testSetGet().
setHrs()
void Time::setHrs (int hrs)
Set hours.
Parameters
new hours
Definition at line 18 of file time.cpp.
 {m_hrs = hrs;}
References m_hrs.
Referenced by testSetGet().
setMins()
void Time::setMins (int mins)
Set minute.
Parameters
new minutes
Definition at line 21 of file time.cpp.
 {m_mins = mins;}
References m_mins.
Referenced by testSetGet().
Member Data Documentation
m_hrs
int Time::m_hrs private
Definition at line 67 of file time.h.
Referenced by getHrs(), getTimeString(), setHrs(), and Time().
m_mins
int Time::m_mins private
Definition at line 66 of file time.h.
Referenced by getMins(), getTimeString(), setMins(), and Time().
The documentation for this class was generated from the following files:
time.h
time.cpp